### ISSUE TITLE
gRIBI client disconnect/close

### ISSUE THREAD

**Issue by sgirishj** [openconfig/featureprofiles#179] opened 2022-05-05 07:30 UTC
I am looking to close/disconnect a gribi client session in the middle of a testcase that requires disconnect/reconnect of the client. The below discussion touches upon this topic and it appears that closing the connection is currently not possible when using the Ondatra API provided client stub for the gribi connection:

https://github.com/openconfig/featureprofiles/pull/106#discussion_r835430782

Could the support for close/disconnect be added please?

**Comment by xw-g** [comment] 2022-05-05 17:54
Hi @sgirishj, which test case/scenario do you think we need to disconnect/close the connection? Can you help provide some reference? Thanks. 

cc: @liulk

**Comment by liulk** [comment] 2022-05-05 18:36
gRIBI connection is actually a streaming call of the Modify() call.

https://github.com/openconfig/gribi/blob/2aaba323cde619765adcb25aae1855b962a4f667/v1/proto/service/gribi.proto#L31

A client is considered disconnected when the streaming call is over. The session is not scoped to the gRPC transport connection. That's why Ondatra API stub never needs to be closed.

As a side note: a gRPC stub may not even correspond to a gRPC transport connection, but it can be load-balanced transparently to multiple gRPC backends, and there could be some load balancing gRPC proxies in between that may choose to reuse existing backend connections or establish new ones. That's why we don't design a protocol using session scoped to the transport connection.

Hope this explanation helps.

**Comment by sgirishj** [comment] 2022-05-06 18:44
Hi @xw-g, this is part of TE-4.2. Pasting a snippet here for reference:

...
...
Establish gRIBI connection to device (referred to asgRIBI-A),setting SINGLE_PRIMARY, and persistence to DELETE.
- Inject an IPv4Entry for 1.0.0.0/8 pointed to a NHG containing a NH of ATE port-2. Ensure that traffic with a destination in 1.0.0.0/8 can be forwarded between ATE port-1 and port-2. Validate AFT entry is installed through telemetry.
- Disconnect the gRIBI-A client, and ensure that traffic can no longer be forwarded for a destination in 1.0.0.0/8 between ATE port-1 and port-2. Validate AFT entry is no longer installed through telemetry.
...
...

@liulk, thanks for the reference. I have a follow up question:
If a client (that connects using SINGLE_PRIMARY and persistence mode DELETE) is to be considered disconnected when the streaming call is over, what is the expected treatment for routes added by the client after such a disconnect? Retain or Delete?

Thanks,
Girish

**Comment by liulk** [comment] 2022-05-06 18:59
@robshakir correct me if I'm wrong, but I think persistence `DELETE` should just delete the routes when the streaming call is over, regardless whether redundancy mode is `SINGLE_PRIMARY` or otherwise.

https://github.com/openconfig/gribi/blob/2aaba323cde619765adcb25aae1855b962a4f667/v1/proto/service/gribi.proto#L384

**Comment by liulk** [comment] 2022-05-09 20:25
> @liulk do you think Ondatra can support API to **cancel** a gRPC call? This would server the same purpose, right?

I don't think you want to cancel gRPC call because it doesn't do what you think it does. Typically, you cancel a gRPC call using a context with a cancel function as constructed by [`context.WithCancel`](https://pkg.go.dev/context#WithCancel). But that just makes the client call return early, and I don't think the server necessarily gets any cancel notification at the wire protocol level.

The way to terminate a bidirectional streaming is [stream.CloseSend()](https://grpc.io/docs/languages/go/basics/#bidirectional-streaming-rpc-1).

By the way, I just noticed that gribigo fluent client doesn't call stream.CloseSend. I'm working on a PR to add it at the appropriate place. The intended behavior is that calling the gribigo fluent client's Close() should be enough to close the gRIBI session.

**Comment by greg-dennis** [comment] 2022-05-10 03:15
gRPC `CloseSend` doesn't terminate a bidirectional stream. It is only a signal the client sends as a courtesy to the server that it intends to send no more messages. The RPC must stay open, though, until one of these 4 conditions are met:
https://github.com/grpc/grpc-go/commit/365770fcbd7dfb9d921cb44827ede770f33be44f

**Comment by sgirishj** [comment] 2022-05-19 22:38
Hi @liulk, I pulled in the changes merged through https://github.com/openconfig/gribigo/pull/143 and tried out. Am not seeing the underlying gRPC session getting terminated/closed. The gRIBI client connection was established with a RawAPI stub using the below function.

https://github.com/openconfig/featureprofiles/blob/main/internal/gribi/gribi.go#L69
------------
func (c *Client) Start(t testing.TB) error {
...
...
	gribiC := c.DUT.RawAPIs().GRIBI().Default(t)
	c.fluentC = fluent.NewClient()
	c.fluentC.Connection().WithStub(gribiC)
...
...
	c.fluentC.Start(ctx, t)
	c.fluentC.StartSending(ctx, t)
...
...
--------------

Could you please share a sample usage to disconnect the transport in this case?

Thanks!

**Comment by liulk** [comment] 2022-05-19 23:12
The disconnect is for the streaming gRPC session of the gRIBI.Modify call, not the underlying gRPC transport. The transport may be load balanced, and the load balancer or proxy may want to keep one transport open to the backend for servicing multiple clients, so closing the transport on the client side does not guarantee that the server will see the transport closing.

**Comment by sgirishj** [comment] 2022-05-25 00:38
Thanks @liulk for the clarification! Will get back if any needed further.

**Closed** 2022-06-08 22:26 UTC

**Comment by amanand** [comment] 2022-06-09 01:20
> > @liulk do you think Ondatra can support API to **cancel** a gRPC call? This would server the same purpose, right?
> 
> I don't think you want to cancel gRPC call because it doesn't do what you think it does. Typically, you cancel a gRPC call using a context with a cancel function as constructed by [`context.WithCancel`](https://pkg.go.dev/context#WithCancel). But that just makes the client call return early, and I don't think the server necessarily gets any cancel notification at the wire protocol level.
> 
> The way to terminate a bidirectional streaming is [stream.CloseSend()](https://grpc.io/docs/languages/go/basics/#bidirectional-streaming-rpc-1).
> 
> By the way, I just noticed that gribigo fluent client doesn't call stream.CloseSend. I'm working on a PR to add it at the appropriate place. The intended behavior is that calling the gribigo fluent client's Close() should be enough to close the gRIBI session.

Hi @liulk/ @greg-dennis  ,
Do you know how to perform sendClose from Python code? I see that if we use a generator for requests in case of client streaming, the last yield results in the GRPC_OP_SEND_CLOSE_FROM_CLIENT. Is there any other way to trigger half close from python client?

**Comment by amanand** [comment] 2022-06-13 14:48
The problem is that at the end of each request iterator, I am seeing the GRPC_OP_SEND_CLOSE_FROM_CLIENT at the server end unlike in the ondatra script where this will be seen when performed stream.CloseSend(). I am not sure if the same asynchronous behavior be achieved in Python. And if its not possible, then addressing this testcase will result in behavioral deviation in different types of clients (i.e go & python).

**Comment by liulk** [comment] 2022-06-13 18:47
I'm not sure I can concur with that observation. Could you put together a minimally reproducible example with a Python bidirectional streaming client? Preferably also show some generated code for the StreamStreamMultiCallable that illustrates the problem that it's not feasible to half-close a bidirectional stream.

https://grpc.github.io/grpc/python/_modules/grpc.html#StreamStreamMultiCallable

If Python is unable to half-close a bidirectional stream, then the Python client *can* resort to closing the gRPC transport, but that means the server won't be able to finish its responses which is quite severe. In any case, I would not call this behavior deviation because both Go and Python clients are still following the same gRPC behavior. Just because Python's generated client code makes it hard to do certain things doesn't mean the server has to treat them differently.
