### ISSUE TITLE
CLI origin test seems to only cover shutdown/no shutdown

### ISSUE THREAD

**Issue by Hobbydos** [openconfig/featureprofiles#335] opened 2022-07-22 21:43 UTC
This seems to be restrictive in case certain vendors do not have `shutdown`, `no shutdown` - Certain vendors have `admin-state disable` and `admin-state enable`. Seen on [L83](https://github.com/openconfig/featureprofiles/blob/main/feature/system/gnmi/cliorigin/ate_tests/cli_origin_test/cli_origin_test.go#L83) and [L89](https://github.com/openconfig/featureprofiles/blob/main/feature/system/gnmi/cliorigin/ate_tests/cli_origin_test/cli_origin_test.go#L89).

**Comment by dplore** [comment] 2022-07-25 04:35
@Hobbydos, feel free to submit a pull request to add support for your vendor/NOS of choice.    You could use this [approach in fptest](https://github.com/openconfig/featureprofiles/blob/5a1aaa3d0a4879b50379c30327ca88cf6b9ac9f1/internal/fptest/ports.go#L25) for now.  We can refactor if/when we converge on some different pattern

**Comment by bstoll** [comment] 2022-08-18 21:47
Closing as a duplicate of #273 / #423.

**Closed by bstoll** 2022-08-18 21:47 UTC
