### ISSUE TITLE
route_propagation_test.go :  NetworkInstance("default") case

### ISSUE THREAD

**Issue by yashikakn** [openconfig/featureprofiles#333] opened 2022-07-21 23:19 UTC
https://github.com/openconfig/featureprofiles/blob/1b105fe0d3bdf7f866dc52aa15e4ea5327be01c1/feature/bgp/addpath/ate_tests/route_propagation_test/route_propagation_test.go#L123 

https://github.com/openconfig/featureprofiles/blob/c5eb74180a2d49a30786123b08518b42af4f9415/feature/bgp/addpath/ate_tests/route_propagation_test/route_propagation_test.go#L130

In the above code, the network-instance case should be 'DEFAULT' than 'default' https://github.com/openconfig/public/blob/e3fa98e0d27cf7fecf75c71d31316f45c83ddfd6/release/models/network-instance/openconfig-network-instance.yang#L1149-L1161

**Comment by aredmon8551** [comment] 2022-07-22 12:55
This is a duplicate of https://github.com/openconfig/featureprofiles/issues/329, @yashikakn can you please close this issue and we'll work through 329?

**Comment by dplore** [comment] 2022-07-25 04:54
Closed in favor of #329

**Closed by dplore** 2022-07-25 04:54 UTC
